[package]
name = "tubefeeder"
version = "0.1.0"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "*"
gtk = "*"
glib = "*"
pango = "*"
relm = "*"
relm-derive = "*"
reqwest = {version = "*", features = ["rustls-tls"], default-features = false}
tokio = {version = "*", features = ["full"]}
quick-xml = {version = "0.21", features = ["serialize"]}
serde = {version = "1.0", features = ["derive"]}
chrono = {version = "*", features = ["serde"]}
# libhandy = "*"
rayon = "*"
futures = "*"

file-minidb = {git = "https://github.com/Schmiddiii/file-minidb.git"}
