[package]
name = "tubefeeder"
version = "1.2.3"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.14.0"
gtk = {version = "0.14.0"}
gdk-pixbuf = "0.14.0"
glib = "0.14.4"
pango = "0.14.3"
relm = "0.22.0"
relm-derive = "0.22.0"
libhandy = "0.8.0"
tokio = {version = "1.2.0", features = ["full"]}
futures = "0.3.13"
regex = "1.5.4"
chrono = {version = "0.4.19"}
csv = "1.1.6"
reqwest = "0.11.4"

log = "0.4.14"
env_logger = "0.9.0"

tf_core = { package = "tubefeeder-extractor-core", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git", tag = "0.1.0" }
tf_yt = { package = "platform-youtube", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git", tag = "0.1.0" }
tf_join = { package = "tubefeeder-extractor-join", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git", tag = "0.1.0" }
tf_filter = { package = "tubefeeder-extractor-filter", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git", tag = "0.1.0" }
tf_observer = { package = "observer", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git", tag = "0.1.0" }
tf_playlist = { package = "playlist", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git", tag = "0.1.1" }

[patch."https://github.com/Tubefeeder/tubefeeder-extractor.git"]
tf_observer = { package = "observer", path = "../tubefeeder-extractor/observer" }
tf_playlist = { package = "playlist", path = "../tubefeeder-extractor/playlist" }
