[package]
name = "tubefeeder"
version = "1.4.0"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.14.0"
gtk = {version = "0.14.0"}
gdk-pixbuf = "0.14.0"
glib = "0.14.4"
pango = "0.14.3"
relm = "0.22.0"
relm-derive = "0.22.0"
libhandy = "0.8.0"
tokio = {version = "1.2.0", features = ["full"]}
futures = "0.3.13"
regex = "1.5.4"
chrono = {version = "0.4.19"}
csv = "1.1.6"
reqwest = "0.11.4"

log = "0.4.14"
env_logger = "0.9.0"

image = "0.23.14"

tf_core = "0.1.1"
tf_join = "0.1.1"
tf_filter = "0.1.1"
tf_observer = "0.1.1"
tf_playlist = "0.1.2"
tf_yt = { package = "tf_platform_youtube", version = "0.1.1" }
tf_pt = { package = "tf_platform_peertube", version = "0.1.0" }
tf_lbry = { package = "tf_platform_lbry", version = "0.1.0" }
