[package]
name = "tubefeeder"
description = "A Youtube-Client made for the Pinephone"
homepage = "https://tubefeeder.de"
version = "1.5.0"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.1", package = "gtk4" }
gdk-pixbuf = "0.14.0"
gdk = { version = "0.4.1", package = "gdk4" }
pango = "0.14.3"
libadwaita = "0.1.0"

tokio = {version = "1.12.0", features = ["full"]}
futures = "0.3.13"
regex = "1.5.4"
chrono = {version = "0.4.19"}
csv = "1.1.6"
reqwest = "0.11.4"

log = "0.4.14"
env_logger = "0.9.0"

image = "0.24.0"
once_cell = "1.0"

gettext-rs = "0.7.0"

tf_core = "0.1.1"
tf_join = "0.1.1"
tf_filter = "0.1.1"
tf_observer = "0.1.1"
tf_playlist = "0.1.2"
tf_yt = { package = "tf_platform_youtube", version = "0.1.1" }
tf_pt = { package = "tf_platform_peertube", version = "0.1.0" }
tf_lbry = { package = "tf_platform_lbry", version = "0.1.0" }
