[package]
name = "tubefeeder"
version = "1.2.3"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.14.0"
gtk = {version = "0.14.0"}
gdk-pixbuf = "0.14.0"
glib = "0.14.4"
pango = "0.14.3"
relm = "0.22.0"
relm-derive = "0.22.0"
libhandy = "0.8.0"

tokio = {version = "1.2.0", features = ["full"]}
futures = "0.3.13"
regex = "1.5.4"

chrono = {version = "0.4.19"}
csv = "1.1.6"

log = "0.4.14"
env_logger = "0.9.0"

tf_core = { package = "tubefeeder-extractor-core", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git" }
tf_yt = { package = "tubefeeder-extractor-youtube", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git" }
tf_join = { package = "tubefeeder-extractor-join", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git" }
tf_filter = { package = "tubefeeder-extractor-filter", git = "https://github.com/Tubefeeder/tubefeeder-extractor.git" }

[patch."https://github.com/Tubefeeder/tubefeeder-extractor.git"]
tf_core = { package = "tubefeeder-extractor-core", path = "../tubefeeder-extractor/tubefeeder-extractor-core" }
tf_yt = { package = "tubefeeder-extractor-youtube", path = "../tubefeeder-extractor/tubefeeder-extractor-youtube" }
tf_join = { package = "tubefeeder-extractor-join", path = "../tubefeeder-extractor/tubefeeder-extractor-join" }
tf_filter = { package = "tubefeeder-extractor-filter", path = "../tubefeeder-extractor/tubefeeder-extractor-filter" }
